# .github/workflows/release.yml
name: All
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    name: Build Release Binaries
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            name: spaceman-${{ github.ref_name }}-x86_64-linux.tar.xz
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            name: spaceman-${{ github.ref_name }}-x86_64-osx.dmg
            os: macos-latest
          - target: aarch64-apple-darwin
            name: spaceman-${{ github.ref_name }}-aarch64-osx.dmg
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            name: spaceman-${{ github.ref_name }}-x86_64-windows.zip
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup | Install Dependencies | Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y \
            build-essential pkg-config libfontconfig1-dev libfontconfig-dev libasound2-dev

      - name: Setup | Install Dependencies | MacOS
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        shell: bash
        run: |
          BUILD_COMMAND="cargo"
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.target }}" != "x86_64-unknown-linux-gnu" ]]; then
            cargo install cross --git https://github.com/cross-rs/cross --tag v0.2.6
            BUILD_COMMAND="cross"
          fi

          $BUILD_COMMAND build --release --locked --target ${{ matrix.target }}

      - name: PostBuild | Prepare | MacOS
        if: matrix.os == 'macos-latest'
        run: |-
          mkdir pkg
          cd pkg
          APP_NAME=spaceman
          MACOS_APP_NAME=SpaceMan
          MACOS_APP_DIR=$MACOS_APP_NAME.app

          echo "Creating app directory structure"
          mkdir -p $MACOS_APP_DIR/Contents/MacOS

          echo "Copying binary"
          cp ../target/${{ matrix.target }}/release/$APP_NAME $MACOS_APP_DIR/Contents/MacOS/$MACOS_APP_NAME

          echo "Creating Icon"
          iconset=AppIcon.iconset
          mkdir -p "${iconset}"

          for s in 16 32 128 256 512; do
            d=$(($s*2))
            sips -Z $s "../spaceman.png" --out "${iconset}/icon_${s}x$s.png"
            sips -Z $d "../spaceman.png" --out "${iconset}/icon_${s}x$s@2x.png"
          done

          iconutil -c icns $iconset
          mkdir -p $MACOS_APP_DIR/Contents/Resources
          mv AppIcon.icns $MACOS_APP_DIR/Contents/Resources/

          cp ../assets/macos/Info.plist $MACOS_APP_DIR/Contents/

          # Set version strings based on tag
          BUILD_NUM=$(echo ${{ github.ref_name }} | sed -E "s/\.//g" | sed -E "s/v0?//")
          SHORT_VER=$(echo ${{ github.ref_name }} | sed -E "s/v//")
          sed -i '' -E "s/\{CFBundleShortVersionString\}/$SHORT_VER/" $MACOS_APP_DIR/Contents/Info.plist
          sed -i '' -E "s/\{CFBundleVersion\}/$BUILD_NUM/" $MACOS_APP_DIR/Contents/Info.plist

          echo "Creating dmg"
          mkdir -p $MACOS_APP_NAME
          cp -r $MACOS_APP_DIR $MACOS_APP_NAME/
          rm -rf $MACOS_APP_NAME/.Trashes

          create-dmg \
            --volname "SpaceMan" \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$MACOS_APP_DIR" 200 190 \
            --hide-extension "$MACOS_APP_DIR" \
            --app-drop-link 600 185 \
            ../${{ matrix.name }} \
            $MACOS_APP_NAME

          cd -

      - name: PostBuild | Prepare | Linux
        if: matrix.os == 'ubuntu-latest'
        run: |-
          mkdir pkg
          cp target/${{ matrix.target }}/release/spaceman pkg/
          cd pkg
          strip ./spaceman || true
          tar -cJvf ../${{ matrix.name }} spaceman
          cd -

      - name: PostBuild | Prepare | Windows
        if: matrix.os == 'windows-latest'
        run: |-
          mkdir spaceman
          cp target/${{ matrix.target }}/release/spaceman.exe spaceman/
          strip spaceman/spaceman.exe || true
          7z a -r ${{ matrix.name }} spaceman

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.name }}
